# Generated by Django 2.2.3 on 2019-07-03 10:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 3, 10, 3, 16, 124319, tzinfo=utc), verbose_name='question date'),
        ),
    ]
