# Generated by Django 2.2.3 on 2019-07-03 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20190703_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='choice_is_correct',
            field=models.BooleanField(default=False),
        ),
    ]
